// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2x_x4EJ29fak3Y0I5_imKLTyJCozxdhc',
    appId: '1:954545725545:web:ab28f91cfbd7aed97482f8',
    messagingSenderId: '954545725545',
    projectId: 'spendifyproject',
    authDomain: 'spendifyproject-2ecbf.firebaseapp.com',
    storageBucket: 'spendifyproject.appspot.com',
    measurementId: 'G-Q9FJRHE3EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqxyfWB3ZFKgk92H0JlR1RUZ8pOltlfok',
    appId: '1:954545725545:android:bc0c67145b374fce7482f8',
    messagingSenderId: '954545725545',
    projectId: 'spendifyproject',
    storageBucket: 'spendifyproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQgZC6VT46FKl5Y1Cp3piRg1a442wjOE',
    appId: '1:954545725545:ios:20dfd4b98599e8b87482f8',
    messagingSenderId: '954545725545',
    projectId: 'spendifyproject',
    storageBucket: 'spendifyproject.appspot.com',
    iosBundleId: 'com.example.spendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQgZC6VT46FKl5Y1Cp3piRg1a442wjOE',
    appId: '1:954545725545:ios:62ab3234e3f356687482f8',
    messagingSenderId: '954545725545',
    projectId: 'spendifyproject',
    storageBucket: 'spendifyproject.appspot.com',
    iosBundleId: 'com.example.spendify.RunnerTests',
  );
}
